import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { AppBar, Toolbar, Button, Box } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppBar position="static" color="default" elevation={1}>
          <Toolbar>
            <Box sx={{ flexGrow: 1 }}>
              <Button component={Link} href="/" color="inherit">Home</Button>
              <Button component={Link} href="/register" color="inherit">Register</Button>
              <Button component={Link} href="/login" color="inherit">Login</Button>
              <Button component={Link} href="/logout" color="inherit">Logout</Button>
            </Box>
          </Toolbar>
        </AppBar>
        {children}
      </body>
    </html>
  );
}
